namespace com.stuffwithstuff.bantam {
   /// <summary>
   /// A simple token class. These are generated by <see cref="Lexer"/>
   /// and consumed by <see cref="Parser"/>.
   /// </summary>
   public sealed class Token {
      public Token(TokenType type, string text) {
         Type = type;
         Text = text;
      }

      public TokenType Type {
         get;
      }

      public string Text {
         get;
      }

      public override string ToString() { return Text; }
   }
}
